spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VendingMachineDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=je2v!he6
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.initialization-mode=never
spring.jpa.hibernate.ddl-auto=none

jwt.secret=je2v!he6

server.port=8080
